---
title: "Final Project"
format: pdf
editor: visual
---

```{r setup, include=F}
library(tidyverse)
```


```{r, message=FALSE}
data = read_csv("Sleep_Analysis.csv")
dim(data)
names(data)
head(data)
```
```{r}
colnames(data) = make.names(colnames(data)) %>% unique()
data = data %>%
  mutate(
    physical.illness = if_else(physical.illness=='no',0,1),
    bluelight.filter = ifelse(bluelight.filter=='no',0,1),
    smoke.drink = ifelse(smoke.drink=='no',0,1),
    meals.day = case_when(
      meals.day=='one'~1,
      meals.day=='two'~2,
      meals.day=='three'~3,
      meals.day=='four'~4,
      meals.day=='five'~5,
      meals.day=='more than 5'~6,
      .default=0
    ),
    screen.time = case_when(
      screen.time=="2hrs"~2,
      screen.time=="3-4 hrs"~3.5,
      screen.time=="1-2 hrs"~1.5,
      screen.time=="2-3 hrs"~2.5,
      screen.time=="4-5 hrs"~4.5,
      screen.time=="more than 5"~5.5,
      screen.time=="0-1 hrs"~0.5,
      .default=0
    )
  )
data
```

# Mean Sleep Duration

```{r}
sleep_time = data %>% 
  dplyr::filter(round(sleep.time,4) != 6.7575) %>% 
  dplyr::select(sleep.time)

sleep_time %>% 
  ggplot() +
    geom_density(aes(x=sleep.time))
```


```{r}
mean(data$sleep.time)
t.test(sleep_time, mu=7)
wilcox.test(sleep_time,mu=7)
```

# Compare male/female
```{r}
data_by_gender = data %>% 
  dplyr::select(Gender, sleep.time) %>%
  dplyr::filter(Gender %in% c("Male", "Female"), round(sleep.time,4) != 6.7575)

data_by_gender %>% 
  ggplot() +
    geom_density(aes(x=sleep.time,color=Gender))
```

```{r}
t.test(sleep.time ~ Gender, data=data_by_gender)
wilcox.test(sleep.time ~ Gender, data=data_by_gender)
```

